import { NextRequest, NextResponse } from "next/server";
import QRCode from "qrcode";
import { CONNECT_URL } from "@/lib/connect";

export const runtime = "nodejs";

// Generates the /connect QR code on demand instead of shipping a static
// binary file in the repo -- encodes ONLY CONNECT_URL (never a specific
// button's link), matching the plan: NFC and QR both point at the one
// permanent card URL, never at LinkedIn/a single vendor link directly.
// Deterministic output (same URL in, same bytes out every time), so a
// long, immutable Cache-Control is safe and this never needs to be
// regenerated by hand when hosting/CDN caches it.
const QR_OPTIONS = {
    errorCorrectionLevel: "H" as const,
    margin: 2,
    color: { dark: "#04070dff", light: "#ffffffff" },
};

export async function GET(_req: NextRequest, { params }: { params: { format: string } }) {
    const { format } = params;

  if (format === "png") {
        const buffer = await QRCode.toBuffer(CONNECT_URL, { ...QR_OPTIONS, type: "png", width: 1024 });
        return new NextResponse(new Uint8Array(buffer), {
                status: 200,
                headers: {
                          "Content-Type": "image/png",
                          "Content-Disposition": 'inline; filename="command-center-ai-connect-qr.png"',
                          "Cache-Control": "public, max-age=31536000, immutable",
                },
        });
  }

  if (format === "svg") {
        const svg = await QRCode.toString(CONNECT_URL, { ...QR_OPTIONS, type: "svg" });
        return new NextResponse(svg, {
                status: 200,
                headers: {
                          "Content-Type": "image/svg+xml",
                          "Content-Disposition": 'inline; filename="command-center-ai-connect-qr.svg"',
                          "Cache-Control": "public, max-age=31536000, immutable",
                },
        });
  }

  return new NextResponse("Not found", { status: 404 });
}
